# Generated by Django 5.0.3 on 2024-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
